<?php if ($this->pageCount): ?>
    <div class="pagination" xmlns="http://www.w3.org/1999/html">
        <ul>
            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
                <li>
                    <a href="<?php echo $this->url($this->route, array('page' => $this->previous)); ?>">
                        < Previous
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled"><span>< Previous</span></li>
            <?php endif; ?>

            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php $class = ($page == $this->current) ? 'class="active"' : '' ?>
                <li <?php echo $class; ?>>
                    <?php if ($page != $this->current): ?>
                        <a href="<?php echo $this->url($this->route, array('page' => $page)); ?>">
                            <?php echo $page; ?>
                        </a>
                    <?php else: ?>
                        <span><?php echo $page; ?></span>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>

            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                <li>
                    <a href="<?php echo $this->url($this->route, array('page' => $this->next)); ?>">
                        Next >
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled"><span>Next ></span></li>
            <?php endif; ?>
        </ul>
    </div>
<?php endif; ?>