<?php
/** @var \Vacancy\Entity\Vacancy $vacancy */
$vacancy = $this->vacancy;
$title = $this->translate('Add translation to vacancy') . ': ' . $vacancy->getTitle();
$this->headTitle($title);
$url = $this->url('translation/add', array('vacancy_id' => $vacancy->getId()));
/** @var \Translation\Form\TranslationEdit $form */
$form = $this->form;
$form->setAttribute('action', $url);
$form->setAttribute('class', 'form-horizontal');
$form->get('description')->setAttribute('style', 'width: 600px;');
$form->prepare();

?>

<h3><?php echo $title; ?></h3>
<hr />
<div class="row">
    <h4><?php echo $vacancy->getTitle(); ?></h4>
    <blockquote><?php echo $vacancy->getDescription(); ?></blockquote>
</div>
<?php echo $this->ztbForm($form); ?>

